{% set name = "pyperf" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dbe0feef8ec1a465df191bba2576149762d15a8c9985c9fea93ab625d875c362

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyperf = pyperf.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - six
    - statistics  # [py2k]

test:
  imports:
    - pyperf
  commands:
    - pyperf --help

about:
  home: http://github.com/vstinner/pyperf/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Toolkit to run Python benchmarks
  doc_url: http://pyperf.readthedocs.io/
  dev_url: https://github.com/vstinner/pyperf/

extra:
  recipe-maintainers:
    - langmm
