{% set name = "pyperf" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ac2e2cf724ab9b525227c3b4a69f16ab5c714ea5bad61c974e0c5d5787238a1

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pyperf = pyperf.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - six
    - statistics  # [py2k]

test:
  imports:
    - pyperf
  commands:
    - pyperf --help

about:
  home: http://github.com/vstinner/pyperf/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Toolkit to run Python benchmarks
  doc_url: http://pyperf.readthedocs.io/
  dev_url: https://github.com/vstinner/pyperf/

extra:
  recipe-maintainers:
    - langmm
